### ISSUE TITLE
Add support for OpenSSL TPM / SSM-based providers 

### ISSUE THREAD

**Issue by jvdprng** [trailofbits/tlslib.py#51]
As per https://discuss.python.org/t/pre-pep-discussion-revival-of-pep-543/51263/47
> Looking at [tpm2-openssl/docs/keys.md at master · tpm2-software/tpm2-openssl · GitHub](https://github.com/tpm2-software/tpm2-openssl/blob/master/docs/keys.md) and [tpm2-openssl/docs/certificates.md at master · tpm2-software/tpm2-openssl · GitHub](https://github.com/tpm2-software/tpm2-openssl/blob/master/docs/certificates.md), wrapping a TPM or SSM based provider in OpenSSL 3+ imposes a similar requirement at least for private keys (so they can be loaded by handle or hardware NV index, rather than from a file).
> 
> While it’s less clear to me if tpm2-openssl itself supports the use of opaque certificates (all the examples given in the docs use regular PEM files for the public certificates), TPM hardware and software security modules certainly offer that feature.

**Comment by woodruffw** [comment]
Done I believe; this is supported via ID-based ctors.
